from pathlib import Path

from recipe.target import *
from toolchain import NativeToolchain, load_or_build_cross_toolchain
from stage import Stage
from build import (
    BuildContext,
    Target,
    detect_machine,
    nproc
)

ctx = BuildContext(
    build_dir               = Path("build").resolve(),
    staging_dir             = Path("build/staging").resolve(),
    metadata_dir            = Path("build/.metadata").resolve(),
    build_machine           = detect_machine(),
    target_machine          = Target.X86_64,
    toolchain               = NativeToolchain(),
    cross_toolchain_dir     = Path("build/toolchain/binaries").resolve(),
    cross_toolchain_sysroot = Path("build/toolchain/sysroot").resolve(),
    num_jobs                = nproc()
)

ctx.toolchain = load_or_build_cross_toolchain(ctx)

Stage(name="base", recipes=[
    RootfsRecipe(),
    GlibCRuntimeRecipe(),
    LibstdcxxRuntimeRecipe(),
    LibgccRuntimeRecipe(),
    ZlibRecipe(),
    XZRecipe(),
    BZip2Recipe(),
    ZStdRecipe(),
    TarRecipe(),
    NcursesRecipe(),
    BashRecipe(),
    CoreutilsRecipe(),
    FindutilsRecipe(),
    GrepRecipe(),
    SedRecipe(),
    GawkRecipe(),
    DiffutilsRecipe(),
    PatchRecipe(),
    UtilLinuxRecipe(),
    GZipRecipe(),
    LessRecipe(),
    WhichRecipe(),
    FileRecipe(),
    ProcpsRecipe(),
    PsmiscRecipe(),
    KmodRecipe(),
    PciutilsRecipe(),
    KernelRecipe(),
    LibxcryptRecipe(),
    LinuxPamRecipe(),
    LibcapRecipe(),
    LibseccompRecipe(),
    GlibRecipe(),
    DbusRecipe(),
    SystemdRecipe(),
    USButilsRecipe(),
    IpRoute2Recipe(),
    NFtablesRecipe(),
    IpUtilsRecipe(),
    OpenSSLRecipe(),
    WgetRecipe(),
    CaCertificateRecipe(),
    CurlRecipe(),
    NetworkManagerRecipe(),
    ShadowRecipe(),
    StraceRecipe(),
    E2fsProgsRecipe(),
    KBDRecipe(),
    IanaEtcRecipe(),
    ReadlineRecipe(),
    ManPagesRecipe(),
    ManDBRecipe(),
    OpenSSHRecipe(),
    IwRecipe(),
    WPASupplicantRecipe(),
    FirmwareRecipe(),
    GettextRecipe(),
    AttrRecipe(),
    ElfutilsRecipe(),
    BcRecipe(),
    M4Recipe(),
    PkgconfRecipe(),
    EfibootmgrRecipe(),
    GrubRecipe(),
    TzdbRecipe(),
    SudoRecipe(),
    NanoRecipe(),
    HwdataRecipe(),
    PartedRecipe(),
    Ntfs3gRecipe(),
]) \
    .build(ctx) \
    .export(ctx, copy=True)